language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: kGFS2KzzlFDhkZKRADoYMt9yX0Mxhfqi/zk+Y96YGoVAhRhBaW6x+MqdpPi04cng/gjiDYZgVZasRajpzlKOHLFSg5Y4Sjxmwsf/lK6cdDCaJvbg5wY+QJ7tHJITLH8zMGlMUsDBHnSU6YiipD6qyIOX8nQW3Oohw+LBV8Ewnm/Ojk7o9ClQ4P+9zSV3Whmkm7uRP2UBnE+BX/0cYK7t+GjD5JKON0GM6xJ0D4ebetBxHtEmVJ/llyE4tJAlGGSjVHRQiwRPXnYxstbR9y+Ez70aBaBkf1oftRQeXQdJUymm3K2j05JetjxlsmO1FK9d7nODiyK3Xf4O9nUdwudJwVY82DDfFAhY/N3d9Y9eeQ7QjPBHMYzZZ9PXqcpjXzvPl/GY7mxk8Ekd28x74xM9Y3bnQPUKSbPhVgX6CBLAjbpaAgGBQcW9lZcQvzC9UsX2krVk8PlhH9KKgoaVthVTjxz0UZHBwrBgxBu1veFCoMyAcv24fsRe9tCtsBF6NNcFKeuBV8ZiU5SSd00LsWpyf17E6CFqPujSffNvvWhjkaP0XS31i7aA+qZETgUXEu4dCYDy02bMGCv1T5GKxKxVDiKIr7pNWIJSWMJGRu0NVapwhuYo8a8avvaAdlhiOLHBaAIocyhQN+1++NVLPaWA/Gl6A+LmHTI12yU8JqO/c+U=
