# .travis.yml
language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: "lc7hbQOv9JewfrPtgmgJ+85ODZR375bp4sDtoa0GAywql1seXVuSWYQQTX3SE7nas6Qo37hnV93ALtljbHLVzoI5iVtxyN5O735Af+JBcJ4taHPInWRYIeEnvZBRrQDxPHFc8dRzUiIbP0Y+ZefPIGu1pynqpLA904AgxEvThG/fIOfmHbCK3xczuVzIkdmKNN8HA3t9adzu9rtR60my7N57ujeXW3yYv76VLeypcrR58FgPlDvplodLQXZbT4hfa6NRqMrFcQAiRxVLMpN4Up6rIPXLKdBvfG89OYH1tnGFDpxyc4KYE+dNCrcPbhW0CCULnPhyVNaDy2gd89VzkQ8Jz7RG+XWG4a27WeQqOBWeEToXWtONxai6B0rIqT1KrdGPivcIPBczmzboMFJ8tXSD+qyoI6ib1F1Fv7WaLb8CY3G0hZbB/1XxJS3cbYRuqRnEnetgkLEjYi750rv5DfO3EXTRKndEA2EHkTBP8aJt9kMwdf7dnt8MzOb4WKkLYjwJCtPbKe6ezBQ+JHaWSQ++57MoLCRcYW6qAL/jl9EeN1/6t+aYPdJzJmX4bnLPnl+TZWiwcneHfvzcCvjjhnh5vUWP64S6EIuiDz1lHpsPCaqy7J3NMx6ZhTECavwB+1Q8aZBudugCTjQzsdAVKf/lcSHTjup07rx9zNV3nsI="
