language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: ZPfEcpQYAoBPDW3/dG8TGO+vLxG+KQHR2pgGIHuY0ZTcO5aHAn4SyPziOG5zIrghviCDCpnvNGehdLdu4bqnkxqBWLSEvJRxD2cNjzNCJz37GLGBwOkTxDqxf7Qv9wZfASAe0xmNHBLwIJKohLsGqIn1Hj1O1pVHJycgsEi7mLtud923S4X8CBHYwbsyWDhmq6mHKBDZWbhfRPHKHGOeTH6/QHJzZWB6E4n7vxVHIU0cf/6dGSffwDiwNG6/s97khK3S02ZTRoW6X42kdxuSVvx+8ymZCYd0rHSlCXCTFKNv1cnYIX/MlCpqJKivhPOBpLKLIODs/O/0hFm1hpQEwTDcXi2xsQ75Cp2g6kD4hYDu1PBYbUceY3rpvLPe0zrG0G5z7psFZFCZumgVdhJor1/MY2n78bXs/75vuOHQUL2jfMjTds40i4PIJBRy461kKFSz0lauWjAdw7Y+sq/RrUoGBlgrf2ciarhTy/2wj30+C1mdhwqU0VuPghL4vBRlob3XUIe1OmD1TX4zOpipQJQoUeisBHdUZPaBmVRyx/uFJBEQ3DtP0dLFacRnPKAcgJVMicodiS0zteNP/EqzYaA9Y1d4NO9Vva6kT+bM6v8DhY3tvu3jAgmu0NjkNdUUG2H3mVGZnvdKw8V8lwnZGpgkALjtYvfFTG+j7SVWZnA=
