# Site settings
url: http://www.disid.com
#url: http://localhost:4000
#baseurl:
email: info@disid.com
google_analytics: UA-1393802-1 #Google analytics code in the format XX-nnnnnnnn-n
ASSET_PATH: /assets
logo: logo-disid-white.png

#Images
master-logo: logo-master-white.png
master-worktool: worktools.png

# Color settings (hex-codes without the leading hash-tag)
# primary_rgb: "59,139,186" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
color:
  primary: 366180
  secondary: 414A52
  secondary-dark: 002436
  light: 7AE2DE

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/disid_corp
  - title: facebook
    url: https://www.facebook.com/DISIDCorp/
  - title: github
    url: https://github.com/DISID
  - title: linkedin
    url: https://www.linkedin.com/company/disid


# Postal address (add as many lines as necessary). Shown in footer on Contact section.
address:
  - lines:
    - Avinguda de Menéndez y Pelayo, 5
    - 46010 Valencia, Spain
email: info@disid.com
email-icon: envelope
tel: (+34) 963 516 309
tel-icon: phone
# Clients information. Shown on Home.
clients:
  - name: Diputación de Valencia
    img: logo-dival.png
    url: http://www.dival.es/
    title: Diputación de Valencia website

# Technologies information. Shown on Home page.
technologies:
  - name: Java
    img: java.png
    title: Java
  - name: Spring
    img: spring.png
    title: Spring
    url: https://spring.io/
  - name: Spring Roo
    img: springroo.png
    title: Spring Roo
    url: https://projects.spring.io/spring-roo/
  - name: gvSIG
    img: gvsig.png
    url: http://www.gvsig.com
    title: Asociación gvSIG website
  - name: Bootstrap
    img: bootstrap.png
    url: http://www.getbootstrap.com
    title: Bootstrap
  - name: "HTML&JS&CSS"
    img: html-js-css.png
    url:
    title: "HTML&JS&CSS"
  - name: JQuery
    img: jquery.png
    url:
    title: "JQuery"
  - name: Thymeleaf
    img: thymeleaf.png
    url:
    title: Thymeleaf
  - name: Maven
    img: maven.png
    url:
    title: Maven
  - name: Hibernate
    img: hibernate.png
    url:
    title: Hibernate
  - name: Liquibase
    img: liquibase.png
    url:
    title: Liquibase
  - name: JUnit
    img: junit.png
    url:
    title: JUnit
  - name: Leaflet
    img: leaflet.png
    url:
    title: Leaflet
  - name: PostgreSQL
    img: postgresql.png
    url:
    title: PostgreSQL
  - name: Docker
    img: docker.png
    url:
    title: Docker

# Build settings
markdown: kramdown
permalink: pretty
permalink: /:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
highlighter: rouge
#paginate:    2
#paginate_path: "blog/page:num"

# jekyll configuration

gems:
  - jekyll-asciidoc

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad

asciidoctor:
  attributes:
    - idseparator=_
    - icons=font-awesome
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style


#
#Multilanguage
#

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: /es
    values:
      lang: es
t:
  en:
    title: "DISID, Be software"
    description: "DISID is a software engineering company specializing in technology, Java platform, Spring IO platform and geomatics."
    intro-lead-in: "Be Software"
    intro-heading: "We are your best choice"
    learn-more: Learn more
    close: Close
    footer-text: Sociedad Limitada 2018 CC BY-NC-SA 3.0 ES | Developed with Jekyll & Bootstrap
    suscribe: Subscribe to stay in the loop
    suscribe-button: Subscribe me!
    contact: Drop us a line
    adress: Address
    phone: Phone
    technologies:
      section-heading: "Our Know-how"
      description: We like to provide technological solutions focused on what really matters to the business and developed on a daily basis. Select the most appropriate technology and tools for the development of each solution. Our base in Java, Spring and always working in a collaborative and evolving the OpenSource, we can offer a solution tailored to what you really need.
    services:
#      section-heading: "Our solutions"
#      section-subheading: "Solutions to and from any device."
    projects:
      section-heading: "Last Projects"
      description: "Find out which technologies move us and what R&D projects motivate us.
      Always on open source, we fix, improve and share our work into the core of the open platforms we use: Liferay, gvNIX, Spring, Spring Roo and gvSIG.
      An active and continued collaboration."
    banner:
      title: "If you have a business project, we will help you to develop it."
      description: "please contact us and we'll assist you with your project's necessities and objectives"
      call-to-action: "Let's talk!"
    banner-team:
      title: "Tell us why you want to work with us"
      description: "Please send your CV with the projects you've worked"
      call-to-action: "Let's talk?"
    banner-master:
      title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      call-to-action: "Let's talk?"
    master:
      button-info: Get more info
      contact: Contact with us
      download-pdf: Download all info
      name-pdf:
      email: masterjava@disid.com
      socialmedia: Redes sociales
      twitter: MasterJava_es
    master-teachers:
      section-heading: "Teachers"
      description:
    master-companies:
      section-heading: "Companies"
      description:
    master-jobs:
      section-heading: "Salidas profesionales"
      description: Una vez terminado el máster, los alumnos saldrán suficientemente preparados para ejercer como analista programador, programador, Scrum Manager, responsable técnico, líder de proyecto de desarrollo o gestor de la demanda entre otros puestos.
    master-why:
      section-heading: "¿Por qué estudiar este Máster?"
      description:

  es:
    title: "DISID, Be Software"
    description: "DISID es una empresa de ingeniería de software especializada en tecnología, plataforma Java, plataforma Spring IO y geomática."
    intro-lead-in: "Be Software"
    intro-heading: "Nosotros somos tu mejor elección"
    learn-more: Saber más
    close: Cerrar
    footer-text: Sociedad Limitada 2013 CC BY-NC-SA 3.0 ES | Sitio web desarrollado con Jekyll & Bootstrap
    suscribe: Suscríbete para mantenerte informado de nuestras noticias
    suscribe-button: ¡Apúntame!
    contact: Queremos escucharte
    adress: Dirección
    phone: Teléfono
    technologies:
      section-heading: "Nuestro soporte para el desarrollo"
      description: Nos gusta facilitar soluciones tecnológicas centradas en lo realmente importante para el negocio y desarrolladas en la base del día a día. Seleccionamos la tecnología y herramientas más apropiadas para el desarrollo de cada solución. Nuestra base en Java, Spring y siempre trabajando en un entorno colaborativo y en constante evolución del OpenSource, nos permite ofrecerte una solución ajustada a lo que realmente necesitas.
    services:
#      section-heading: "Nuestras soluciones"
#      section-subheading: "Soluciones desde y para cualquier dispositivo."
    projects:
      section-heading: "Nuestros Proyectos"
      description: "Entérate de primera mano sobre qué tecnologías nos movemos y qué proyectos nos motivan.
      Siempre sobre código abierto, desarrollamos mejoras e implementaciones sobre nuestras plataformas de desarrollo Liferay, gvNIX, Spring Roo y gvSIG.
      Una participación activa y continuada."
    banner:
      title: "Si tienes una idea de negocio, te ayudamos a desarrollarla."
      description: "Ponte en contacto con nosotros y te asesoramos con tu proyecto"
      call-to-action: "¿Hablamos?"
    banner-team:
      title: "Cuéntanos por qué quieres trabajar con nosotros"
      description: "Envíanos tu CV con los proyectos en los que has trabajado"
      call-to-action: "¿Hablamos?"
    banner-master:
      title: "¿Te apuntas?"
      description: "Formáte con nostros y mejora tu carrera profesional"
      call-to-action: "Recibir más información"
    master:
      button-info: Quiero más información
      contact: Contacta con nosotros
      download-pdf: Descarga toda la información
      name-pdf:
      email: masterjava@disid.com
      socialmedia: Redes sociales
      twitter: MasterJava_es
    master-teachers:
      section-heading: "Profesores"
      description:
    master-companies:
      section-heading: "Empresas que forman la bolsa de empleo"
      description:
    master-jobs:
      section-heading: "Salidas profesionales"
      description: Una vez terminado el máster, los alumnos saldrán suficientemente preparados para ejercer como analista programador, programador, Scrum Manager, responsable técnico, líder de proyecto de desarrollo o gestor de la demanda entre otros puestos.
    master-why:
      section-heading: "¿Por qué estudiar este Máster?"
      description:


# To include variable in liquid: {{ site.t[page.lang].labs.section-heading }}
# You can add translations group

# Links to include in top navigation
# For external links add external: true/false
links:
  en:
    solutions:
      title: Solutions
      url: "http://www.disid.com#solutions"
    projects:
      title: Projects
      url: "http://www.disid.com#projects"
#    master:
#      title: Master
#      url: "http://www.disid.com#master"
    technologies:
      title: Technologies
      url: "http://www.disid.com#technologies"
    blog:
      title: Blog
      url: "http://blog.disid.com/"
      external: true
    contact:
      title: Contact
      url: "http://www.disid.com#contact"
  es:
    solutions:
      title: Soluciones
      url: "http://www.disid.com#solutions"
    projects:
      title: Proyectos
      url: "http://www.disid.com#projects"
    master:
      title: Máster
      url: "http://www.disid.com#master"
    technologies:
      title: Tecnologías
      url: "http://www.disid.com#technologies"
    blog:
      title: Blog
      url: "http://blog.disid.com/es/index.html"
      external: true
    contact:
      title: Contacto
      url: "http://www.disid.com#contact"

linksextra:
  en:
    jobs:
      title: Jobs
      url: "/jobs"
    notice:
      title: Legal notice
      url: "/legal-notice"
#    terms:
#      title: Terms of use
#      url: "/terms-of-use"
    cookies:
      title: Cookies
      url: "/cookies-policy"
    privacy:
      title: Privacy policy
      url: "/privacy-policy"
  es:
    jobs:
      title: Empleo
      url: "/jobs"
    notice:
      title: Aviso legal
      url: "/aviso-legal"
#    terms:
#      title: Condiciones de uso
#      url: "/terms-of-use"
    cookies:
      title: Cookies
      url: "/politica-de-cookies"
    privacy:
      title: Política de privacidad
      url: "/politica-de-privacidad"


# Links to include in master navigation
master-links:
  en:
    description:
      title: Description
      url: "#description"
    agenda:
      title: Agenda
      url: "#agenda"
    teachers:
      title: Teachers
      url: "#teachers"
    employment:
      title: Employment and internships
      url: "#job-works"
  es:
    description:
      title: Descripción
      url: "#description"
    agenda:
      title: Temario
      url: "#agenda"
    teachers:
      title: Profesores
      url: "#teachers"
    employment:
      title: Empleo y prácticas
      url: "#training"
    about:
      title: Qué nos diferencia
      url: "#about"
    why:
      title: Por qué elegirnos
      url: "#why"

# Teachers information. Shown on Master page.
teachers:
  es:
    - name: David Peña
      img: dpena.png
      title: Director, coordinador y profesor del máster
    - name: Enrique Ruiz
      img: eruiz.png
      title: Subdirector del máster
      #url:
    - name: Juan Carlos García
      img: jgarcia.png
      title: Profesor Seminario Spring Roo
      job: Software Architect en DISID
      #url:
    - name: Luis Mahiques
      img: lmahiques.jpeg
      title: Profesor Java, Spring y DevOps
      #url:
    - name: Carlos Cabanes
      img: ccabanes.png
      title: Profesor Seminario GIS
      job: Director de proyectos en DISID
      #url:
    - name: Jorge Sánchez
      img: jsanchez.png
      title: Profesor seminario Scrum
      job: Trainer Oficial Scrum Manager
      #url:
    - name: Jorge Edo
      img: jedo.png
      title: Profesor seminario ITIL
      job: Trainer Oficial Axelos ITIL
      #url:

# Companies information. Shown on Master page.
companies:
    - name: Alfatec
      img: alfatec.png
      title:
      url: http://www.alfatecsistemas.es
    - name: EDICOM
      img: edicom.png
      title:
      url: http://www.edicomgroup.com
    - name: ODEC
      img: odec.png
      title:
      url: http://www.odec.es
    - name: Pentec
      img: pentec.png
      title:
      url: http://www.pentec.es
    - name: S2 Grupo
      img: s2grupo.png
      title:
      url: http://www.s2grupo.es
    - name: DISID
      img: disid.png
      title:
      url: http://www.disid.com

#Collection
collections:
  master-featured:
    output: false
    #permalink: /about/:path/
  master-agenda:
    output: false
    #permalink: /agenda/:path/
  master-job:
    output: false
    #permalink: /agenda/:path/
  master-why:
    output: false
    #permalink: /agenda/:path/
  master-about:
    output: false
    #permalink: /agenda/:path/

include: [".htaccess"]
exclude: ["slides","vendor", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
